name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          kill -9 $(lsof -i:8080)
          cd ~/app/2023_1_WAT_BeJuRyu/backend
          git pull origin develop_server
          rm ./src/main/resources/application.properties
          echo "${{ secrets.PROPERTIES }}" >> ./src/main/resoucres/application.properties
          ./gradlew bootJar
          cd build/libs
          nohup java -jar BEJURYU-0.0.1-SNAPSHOT.jar > nohup.out 2> nohup.err < /dev/null &
          
