name: deploy
 jobs:
   build:
     name: deploy
     runs-on: ubuntu-latest
     steps:
       - name: executing remote ssh commands using key
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.KEY }}
	   password: ${{ secrets.PASSWORD }}
           port: 22
           script: |
             kill -9 $(lsof -i:8080)
             cd ~/app/2023_1_WAT_BeJuRyu/backend
             git pull origin develop_server
             ./gradlew bootJar
             cd build/libs
             nohup java -jar BEJURYU-0.0.1-SNAPSHOT.jar &
